export const ACTION_TYPE = {
    ACCESS_TOKEN: 'ACCESS_TOKEN',
    REFRESH_TOKEN_KEY:'REFRESH_TOKEN_KEY',
    USER_DATA: 'USER_DATA',
    USER_LOCATION: 'USER_LOCATION',
    
};

export const ACTION_STATUS = {
    LOGIN_TWITTER: 'LOGIN_TWITTER',
    LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',
    LOGIN_GOOGLE: 'LOGIN_GOOGLE',
    LOGIN_NOT_SOCIAL: 'LOGIN_NOT_SOCIAL'
};
